---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
        - name: wait-30s
          image: busybox:latest
          command: ['sh', '-c', "sleep 10"]
      containers:
        - image: quay.io/packit/nginx-unprivileged:1.21.6
          imagePullPolicy: IfNotPresent
          name: nginx
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
               - ALL
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
      restartPolicy: Always
