---
apiVersion: v1
kind: LimitRange
metadata:
  name: enforce-requests-and-limits
spec:
  limits:
  - default:
      memory: 256Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container
