---
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-1002
spec:
  securityContext:
    runAsUser: 1002
    runAsGroup: 3000
  containers:
    - name: sec-ctx-demo
      image: busybox:latest
      command: [ "sh", "-c", "sleep 1h" ]
      volumeMounts:
        - name: sec-ctx-vol
          mountPath: /data/demo
      securityContext:
        allowPrivilegeEscalation: false
  volumes:
    - name: sec-ctx-vol
      persistentVolumeClaim:
        claimName: security-context-demo
