---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-context-demo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
