---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      # note that there is no delete in this list
      - get
      - list
      - create
      - update
