---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch_deployment.json
    target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deployment
  - path: patch_configMap.yml
    target:
      group: ""
      version: v1
      kind: ConfigMap
      name: nginx-index-html
