apiVersion: apps/v1
kind: Deployment
metadata:
  name: yellow-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yellow-nginx
  template:
    metadata:
      labels:
        app: yellow-nginx
    spec:
      containers:
        - name: yellow-nginx
          image: nginx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: color
                    operator: In
                    values:
                      - yellow
